[package]
name = "whynot-errors"
version = "0.2.0"
edition = "2021"
description = "A basic setup for app errors in axum"
license = "MIT"
repository = "https://github.com/whynotavailable/whynot-errors"

[dependencies]
axum = "~0.8.1"
